#!/usr/bin/env bash
#
# SSG (Static Site Generator) for Swirc homepage.
# Copyright (C) 2017-2019 Markus Uhlin. ALL RIGHTS RESERVED.

source "include/check_sections.sh"
source "include/pages.sh"
source "include/dirs.sh"
source "include/images.sh"
source "include/screenshots.sh"
source "include/themes.sh"
source "include/other_files.sh"
source "include/transfer_site.sh"

check_sections
check_pages
check_dirs
check_images
check_screenshots
check_themes
check_other_files

TEMP_DIR=$(mktemp -d)

create_dirs "$TEMP_DIR"
gen_pages "$TEMP_DIR"
add_images "$TEMP_DIR"
add_screenshots "$TEMP_DIR"
add_themes "$TEMP_DIR"
add_other_files "$TEMP_DIR"

while true; do
	read -p "Transfer the statically generated site? [Y/n]: " -r choice

	if test -z "$choice" -o "$choice" = y -o "$choice" = Y; then
		transfer_site
		break
	elif test "$choice" = n -o "$choice" = N; then
		break
	else
		continue
	fi
done

echo "Done"
