#!/usr/bin/env bash

source "VERSION_INFO"

TGZ=/tmp/swirc-${VERSION}.tgz

if [ "$1" = "--head" ]; then
	echo "warning: archiving HEAD as $VERSION"
	git archive --format=tgz --prefix=swirc-${VERSION}/ -o $TGZ HEAD
else
	git archive --format=tgz --prefix=swirc-${VERSION}/ -o $TGZ v$VERSION
	gpg -o ${TGZ}.sig -a -b $TGZ
fi

if [ -f "$TGZ" ]; then
	echo "$TGZ created"
fi

if [ -f "${TGZ}.sig" ]; then
	echo "${TGZ}.sig created"
fi
