#!/usr/bin/env bash

source "VERSION_INFO"

source "bash/edit_changelog.sh"
source "bash/edit_debian_changelog.sh"
source "bash/edit_dot_wxs.sh"
source "bash/edit_main_cpp.sh"
source "bash/edit_po_file.sh"
source "bash/edit_ports_makefile.sh"
source "bash/edit_rc_file.sh"
source "bash/edit_vc_makefile.sh"
source "bash/edit_void_template.sh"

edit_changelog		"CHANGELOG.md"
#edit_debian_changelog	"debian/changelog"
edit_dot_wxs		"Swirc.wxs"
edit_main_cpp		"src/main.cpp"
edit_po_file		"po/de/swirc.po"
edit_po_file		"po/fi/swirc.po"
edit_po_file		"po/fr/swirc.po"
edit_po_file		"po/sv/swirc.po"
edit_ports_makefile	"openbsd/Makefile"
edit_rc_file		"src/swirc.rc"
edit_vc_makefile	"Makefile.vc"
edit_void_template	"voidlinux/template"

echo "Done"
