#!/bin/sh

SWIRC_PATH=/usr/ports/net/swirc

install -d $SWIRC_PATH
install -d $SWIRC_PATH/patches
install -d $SWIRC_PATH/pkg
install -m 0644 Makefile $SWIRC_PATH
install -m 0644 patches/patch-install_mk $SWIRC_PATH/patches
install -m 0644 pkg/DESCR $SWIRC_PATH/pkg
echo "Done"
