#!/usr/bin/env bash

TESTS="
cmd_ban
cmd_deop
cmd_kick
cmd_op
cmd_part
cmd_unban
int_diff
int_sum
is_alphabetic
is_numeric
realloc_strcat
size_product
squeeze
squeeze_text_deco
strColor
strFeed
strToLower
strToUpper
strdup_printf
sw_snprintf
sw_strcat
sw_strcpy
sw_strdup
sw_wcscat
sw_wcscpy
trim
write_to_stream
"

for test in $TESTS; do
    test -x "${test}.run" && "./${test}.run"
done
