#!/usr/bin/env bash

TESTS="
cmd_ban
cmd_deop
cmd_kick
cmd_op
cmd_part
cmd_servlist
cmd_squery
cmd_unban
cmd_znc
crypt
destroy_null_bytes
getuser
icb_send_pm
int_diff
int_sum
isValid
is_alphabetic
is_numeric
printtext_convert_wc
realloc_strcat
rot13
size_product
squeeze
squeeze_text_deco
strColor
strFeed
strToLower
strToUpper
strdup_printf
sw_snprintf
sw_strcat
sw_strcpy
sw_strdup
sw_wcscat
sw_wcscpy
trim
write_to_stream
xstrnlen
"

for test in $TESTS; do
	test -x "${test}.run" && "./${test}.run"
done
