TESTS = cmd_ban.run\
	cmd_deop.run\
	cmd_kick.run\
	cmd_op.run\
	cmd_part.run\
	cmd_servlist.run\
	cmd_squery.run\
	cmd_unban.run\
	cmd_znc.run\
	crypt.run\
	getuser.run\
	icb_send_pm.run\
	int_diff.run\
	int_sum.run\
	is_alphabetic.run\
	is_numeric.run\
	realloc_strcat.run\
	rot13.run\
	size_product.run\
	squeeze.run\
	squeeze_text_deco.run\
	strColor.run\
	strFeed.run\
	strToLower.run\
	strToUpper.run\
	strdup_printf.run\
	sw_snprintf.run\
	sw_strcat.run\
	sw_strcpy.run\
	sw_strdup.run\
	sw_wcscat.run\
	sw_wcscpy.run\
	trim.run\
	write_to_stream.run\
	xstrnlen.run
