COMMANDS_DIR := src/commands/
COMMANDS_SRCS = $(COMMANDS_DIR)admin.cpp\
	$(COMMANDS_DIR)announce.cpp\
	$(COMMANDS_DIR)ban.c\
	$(COMMANDS_DIR)cap.cpp\
	$(COMMANDS_DIR)cleartoasts.cpp\
	$(COMMANDS_DIR)colormap.cpp\
	$(COMMANDS_DIR)connect.c\
	$(COMMANDS_DIR)ctcp.c\
	$(COMMANDS_DIR)dcc-unix.cpp\
	$(COMMANDS_DIR)dcc.cpp\
	$(COMMANDS_DIR)echo.c\
	$(COMMANDS_DIR)fetchdic.cpp\
	$(COMMANDS_DIR)ftp-unix.cpp\
	$(COMMANDS_DIR)ftp.cpp\
	$(COMMANDS_DIR)ignore.cpp\
	$(COMMANDS_DIR)info.cpp\
	$(COMMANDS_DIR)invite.c\
	$(COMMANDS_DIR)jp.cpp\
	$(COMMANDS_DIR)kick.c\
	$(COMMANDS_DIR)log.cpp\
	$(COMMANDS_DIR)me.c\
	$(COMMANDS_DIR)misc.c\
	$(COMMANDS_DIR)msg.c\
	$(COMMANDS_DIR)nick.c\
	$(COMMANDS_DIR)notice.cpp\
	$(COMMANDS_DIR)op.c\
	$(COMMANDS_DIR)sasl-scram-sha.cpp\
	$(COMMANDS_DIR)sasl.cpp\
	$(COMMANDS_DIR)say.c\
	$(COMMANDS_DIR)services.cpp\
	$(COMMANDS_DIR)servlist.cpp\
	$(COMMANDS_DIR)squery.cpp\
	$(COMMANDS_DIR)theme.c\
	$(COMMANDS_DIR)topic.c\
	$(COMMANDS_DIR)utctime.cpp\
	$(COMMANDS_DIR)voice.c\
	$(COMMANDS_DIR)wholeft.cpp\
	$(COMMANDS_DIR)znc.cpp

OBJS = $(COMMANDS_DIR)admin.o\
	$(COMMANDS_DIR)announce.o\
	$(COMMANDS_DIR)ban.o\
	$(COMMANDS_DIR)cap.o\
	$(COMMANDS_DIR)cleartoasts.o\
	$(COMMANDS_DIR)colormap.o\
	$(COMMANDS_DIR)connect.o\
	$(COMMANDS_DIR)ctcp.o\
	$(COMMANDS_DIR)dcc-unix.o\
	$(COMMANDS_DIR)dcc.o\
	$(COMMANDS_DIR)echo.o\
	$(COMMANDS_DIR)fetchdic.o\
	$(COMMANDS_DIR)ftp-unix.o\
	$(COMMANDS_DIR)ftp.o\
	$(COMMANDS_DIR)ignore.o\
	$(COMMANDS_DIR)info.o\
	$(COMMANDS_DIR)invite.o\
	$(COMMANDS_DIR)jp.o\
	$(COMMANDS_DIR)kick.o\
	$(COMMANDS_DIR)log.o\
	$(COMMANDS_DIR)me.o\
	$(COMMANDS_DIR)misc.o\
	$(COMMANDS_DIR)msg.o\
	$(COMMANDS_DIR)nick.o\
	$(COMMANDS_DIR)notice.o\
	$(COMMANDS_DIR)op.o\
	$(COMMANDS_DIR)sasl-scram-sha.o\
	$(COMMANDS_DIR)sasl.o\
	$(COMMANDS_DIR)say.o\
	$(COMMANDS_DIR)services.o\
	$(COMMANDS_DIR)servlist.o\
	$(COMMANDS_DIR)squery.o\
	$(COMMANDS_DIR)theme.o\
	$(COMMANDS_DIR)topic.o\
	$(COMMANDS_DIR)utctime.o\
	$(COMMANDS_DIR)voice.o\
	$(COMMANDS_DIR)wholeft.o\
	$(COMMANDS_DIR)znc.o

CPPFLAGS += -I $(COMMANDS_DIR)
