#!/bin/sh

SWIRC_PATH=/usr/ports/net/swirc

install_patches () {
	_patches=""

	for p in $_patches; do
		install -m 0644 "patches/$p" $SWIRC_PATH/patches
	done
}

cd /usr
cvs -d anoncvs@anoncvs.fr.openbsd.org:/cvs checkout -P ports/net/swirc

cd -
install -d $SWIRC_PATH
install -d $SWIRC_PATH/patches
install -d $SWIRC_PATH/pkg
install -m 0644 Makefile $SWIRC_PATH
install_patches
install -m 0644 pkg/DESCR $SWIRC_PATH/pkg
install -m 0644 pkg/PLIST $SWIRC_PATH/pkg

echo "Done"
