.\"
.\" Public domain
.\"
.Dd November 4, 2018
.Dt SWIRC 1
.Os
.Sh NAME
.Nm swirc
.Nd cool curses irc client
.Sh SYNOPSIS
.Nm swirc
.Bk -words
.Op OPTION
.Op ...
.Ek
.Sh DESCRIPTION
.Nm
is a text-mode IRC client whose goals are to be portable, and to
provide a secure and user-friendly experience to its users.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c Ar server[:port]
Auto-connect to given server.
If the port is omitted port 6667 will be chosen.
And if the port is 6697 the program attempts to initiate a TLS/SSL
connection.
.It Fl n Ar nickname
Online nickname
.It Fl u Ar username
User identity
.It Fl r Ar rl name
Specifies the real name
.It Fl i
ICB mode (Internet Citizen's Band, currently not implemented)
.It Fl p
Server password (for private servers). However: InspIRCd has a module
called password forward, which means that if a server password is
specified by this flag, it will be used to identify to
.Em NickServ .
If so: connect with a TLS/SSL connection, i.e. an encrypted
connection, to prevent your password from being sniffed.
.Nm
also supports IRCv3 SASL authentication which is probably a better
alternative.
.It Fl h Ar hostname
Use this hostname on connect (currently a no-op)
.It Fl x Ar config
Explicit config file
.It Fl version
View the current client version
.It Fl help
Print the usage
.El
.Sh KEY COMBOS
.Bl -tag -width "          " -compact
.It Ic CTRL+a
Move to beginning of line
.It Ic CTRL+e
Move to end of line
.It Ic CTRL+b
Move cursor backward
.It Ic CTRL+f
Move cursor forward
.It Ic CTRL+d
Delete
.It Ic CTRL+g
Clear readline input
.It Ic CTRL+n
Next window
.It Ic CTRL+p
Previous window
.It Ic PG UP
Scroll up
.It Ic PG DOWN
Scroll down
.It Ic Up arrow
History previous
.It Ic Down arrow
History next
.It Ic F11
Close window
.It Ic F12
Close all private conversations
.El
.Sh INSERTING TEXT-DECORATION
.Bl -tag -width "          " -compact
.It Ic F5
Blink
.It Ic F6
Bold
.It Ic F7
Color
.It Ic F8
Normal
.It Ic F9
Reverse
.It Ic F10
Underline
.El
.Sh MITIGATIONS
On
.Ox
.Xr pledge 2
is used per default in order to force
.Nm
into a restricted-service operating mode.
This since version 1.1.
Further, as of 2.3,
.Xr pledge 2
is used in combination with
.Xr unveil 2 .
.Sh FILES
.Bl -tag -width "                         " -compact
.It Pa ~/.swirc/swirc.conf
.Nm
configuration file
.It Pa ~/.swirc/default.the
.Nm
default theme
.It Pa ~/.swirc/log/error.log
.Nm
error log
.El
.Sh SEE ALSO
.Xr swirc.conf 5
.Sh AUTHORS
.Nm
was written by
.An Markus Uhlin
.Aq Mt markus.uhlin@bredband.net
.Sh BUGS
.Lk https://github.com/uhlin/swirc/issues
.Pp
If many errors regarding
"In perform_convert_buffer: characters lost: Illegal byte sequence"
are present in the error log, then additional encodings for your
locale should be installed.
See
.Xr locale 1
for supported character encodings.
.Nm
can handle and are looking for:
.Pp
.Bl -dash -compact
.It
UTF-8
.It
ISO-8859-1
.It
ISO-8859-15
.El
.Pp
Unfortunately some operating systems have decided to only support the
UTF-8 character encoding.
