.\"
.\" Public domain
.\"
.Dd August 24, 2021
.Dt SWIRC 1
.Os
.Sh NAME
.Nm swirc
.Nd curses icb and irc client
.Sh SYNOPSIS
.Nm swirc
.Bk -words
.Op Fl 46?CPRdipv
.Op Fl c Ar server[:port]
.Op Fl n Ar nickname
.Op Fl r Ar rl name
.Op Fl u Ar username
.Op Fl x Ar config
.Ek
.Sh DESCRIPTION
.Nm
is a BSD licensed, console based and lightweight ICB and IRC client
written in C/C++, whose goals are to be portable and secure.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl 4
Use IPv4 addresses only
.It Fl 6
Use IPv6 addresses only
.It Fl ?
Output help
.It Fl C
Do not change color definitions.
If the terminal used to run
.Nm
supports >= 256 colors and
.Xr can_change_color 3
is true
.Nm
uses
.Xr init_color 3
to initialize the extended IRC color palette.
Which may or may not already be set correctly by the terminal.
This option is useful in case the terminal look strange after exit,
which is possible to fix by simply restarting it.
.It Fl P
Permanently disable SASL authentication.
If specified, the effect is \fIfinal\fP (i.e. it overrides any config
file value.)
.It Fl R
Disable TLS/SSL peer verification
.It Fl c Ar server[:port]
Connect to given server.
If the port is omitted port 6667 will be chosen.
And if the port is 7326 ICB mode is turned on automatically.
Further, if the port is 6697
.Nm
attempts to initiate a TLS/SSL connection.
.It Fl d
Debug logging
.It Fl i
Turn on Internet Citizen's Band mode
.It Fl n Ar nickname
Online nickname
.It Fl p
Server password (for private servers). However: InspIRCd has a module
called password forward, which means that if a server password is
specified by this flag, it will be used to identify to
.Em NickServ .
If so: connect with a TLS/SSL connection, i.e. an encrypted
connection, to prevent your password from being disclosed in clear
text.
.Nm
also supports IRCv3 SASL authentication which is probably a better
alternative.
.It Fl r Ar rl name
Your real name
.It Fl u Ar username
Your username
.It Fl v
Output
.Nm
version
.It Fl x Ar config
Config file
.El
.Sh KEYS
.Bl -tag -width "          " -compact
.It Ic CTRL+a
Move to beginning of line
.It Ic CTRL+e
Move to end of line
.It Ic CTRL+b
Move cursor backward
.It Ic CTRL+f
Move cursor forward
.It Ic CTRL+d
Delete
.It Ic CTRL+g
Clear readline input.
Also useful to trigger terminal resize signal.
.It Ic CTRL+l
Per window basis toggle logging on/off and works while IRC connected
.It Ic CTRL+n
Next window
.It Ic CTRL+p
Previous window
.It Ic PG UP
Scroll up
.It Ic PG DOWN
Scroll down
.It Ic Up arrow
History previous
.It Ic Down arrow
History next
.It Ic F3
Scroll nicklist up
.It Ic F4
Scroll nicklist down
.It Ic F11
Close window
.It Ic F12
Close all private conversations
.El
.Sh INSERTING TEXT-DECORATION
.Bl -tag -width "          " -compact
.It Ic F5
Blink
.It Ic F6
Bold
.It Ic F7
Color
.It Ic F8
Normal
.It Ic F9
Reverse
.It Ic F10
Underline
.El
.Sh MITIGATIONS
On
.Ox
.Xr pledge 2
is used per default in order to force
.Nm
into a restricted-service operating mode.
This since version 1.1.
Further, as of 2.3,
.Xr pledge 2
is used in combination with
.Xr unveil 2 .
.Sh FILES
.Bl -tag -width "                         " -compact
.It Pa ~/.swirc/swirc.conf
.Nm
configuration file
.It Pa ~/.swirc/default.the
.Nm
default theme
.It Pa ~/.swirc/log/error.log
.Nm
error log
.El
.Sh SEE ALSO
.Xr swirc.conf 5
.Sh AUTHORS
.Nm
was written by
.An Markus Uhlin
.Aq Mt markus.uhlin@bredband.net
.Sh BUGS
.Lk https://github.com/uhlin/swirc/issues
.Pp
If many errors regarding
.Qo
In perform_convert_buffer: characters lost: Illegal byte sequence
.Qc
are present in the error log, then additional encodings for your
locale should be installed.
See
.Xr locale 1
for supported character encodings.
.Nm
can handle and are looking for:
.Pp
.Bl -dash -compact
.It
UTF-8
.It
ISO-8859-1
.It
ISO-8859-15
.El
.Pp
Unfortunately some operating systems have decided to only support the
UTF-8 character encoding.
